[package]
name = "omfg"
version = "0.1.0"
authors = ["Arne Beer <contact@arne.beer>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy-table = "^0"
