[package]
name = "comfy-table"
description = "A easy to use, automatically wrapping and highly configurable commandline table builder library."
version = "0.0.3"
authors = ["Arne Beer <contact@arne.beer>"]
homepage = "https://github.com/nukesor/comfy-table"
repository = "https://github.com/nukesor/comfy-table"
documentation = "https://docs.rs/comfy-table/"
license = "MIT"
keywords = ["shell", "commandline", "table", "unicode"]
readme = "README.md"
edition = "2018"
build = "build.rs"

[badges]
travis-ci = { repository = "nukesor/comfy-table", branch = "master" }
maintenance = { status = "actively-developed" }


[dependencies]
atty = "^0.2"
crossterm = "^0.14"
strum = "^0.17"
strum_macros = "^0.17"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
pretty_assertions = "0.6"
skeptic = "0.13"
proptest = "0.9.0"
