[package]
name = "comfy-table"
description = "An easy to use library for building beautiful tables with automatic content wrapping"
version = "1.4.0"
authors = ["Arne Beer <contact@arne.beer>"]
homepage = "https://github.com/nukesor/comfy-table"
repository = "https://github.com/nukesor/comfy-table"
documentation = "https://docs.rs/comfy-table/"
license = "MIT"
keywords = ["shell", "commandline", "table", "unicode"]
readme = "README.md"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
crossterm = "^0.18"
strum = "^0.19"
strum_macros = "^0.19"

[dev-dependencies]
pretty_assertions = "0.6"
doc-comment = "0.3"
proptest = "0.10.0"
