name: Coverage

on:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Create coverage statistics
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v1

    - run: cargo build
    - run: cargo test --verbose
    - run: cargo install cargo-tarpaulin
    - run: cargo tarpaulin --out Xml
    - run: bash <(curl -s https://codecov.io/bash)
