name: Coverage

on:
  push:
    branches:
      - master

jobs:
  coverage:
    name: Create coverage statistics
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v1

    - run: cargo build
    - run: cargo test --verbose
    - run: cargo install cargo-tarpaulin
    - run: cargo tarpaulin --out Xml

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./cobertura.xml
        fail_ci_if_error: true
