name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Tests for ${{ matrix.os }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable, nightly]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test --verbose
