name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Tests for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v1

    - run: cargo test --verbose
    - run: cargo build
